"""Storage interface.

Two implementations exist:

* :class:`app.db.postgres.PostgresRepository` - PostgreSQL + pgvector (HNSW,
  cosine) + ``tsvector`` full-text search with BM25 scoring evaluated in SQL.
* :class:`app.db.memory.InMemoryRepository` - numpy cosine similarity + a
  Python BM25 index; zero infrastructure, used for tests and quick local runs.

Retrieval code only talks to this protocol, so both backends are exercised by
the same engine and the same evaluation harness.
"""

from __future__ import annotations

from typing import Protocol

import numpy as np

from app.models.domain import Chunk, Document, Entity, Mention, Relationship, ResolutionDecision


class Repository(Protocol):
    backend_name: str

    # ---- documents & chunks
    def add_document(self, document: Document, chunks: list[Chunk], mentions: list[Mention]) -> None: ...
    def find_duplicate(self, filename: str, content_hash: str) -> Document | None: ...
    def get_document(self, document_id: str) -> Document | None: ...
    def list_documents(self) -> list[Document]: ...
    def delete_document(self, document_id: str) -> bool: ...
    def get_chunks(self, chunk_ids: list[str]) -> dict[str, Chunk]: ...
    def get_document_chunks(self, document_id: str) -> list[Chunk]: ...
    def get_embeddings(self, chunk_ids: list[str]) -> dict[str, np.ndarray]: ...
    def all_chunk_ids(self) -> list[str]: ...
    def counts(self) -> dict[str, int]: ...
    def finalize_ingest(self) -> None:
        """Refresh derived statistics/indexes after a batch of writes."""
        ...

    def reset(self) -> None: ...

    # ---- retrieval primitives
    def lexical_search(self, query: str, k: int) -> list[tuple[str, float]]: ...
    def lexical_scores(self, query: str, chunk_ids: list[str]) -> dict[str, float]: ...
    def vector_search(self, embedding: np.ndarray, k: int) -> list[tuple[str, float]]: ...
    def vector_scores(self, embedding: np.ndarray, chunk_ids: list[str]) -> dict[str, float]: ...
    def term_document_frequencies(self, terms: list[str]) -> tuple[dict[str, int], int]: ...
    def unknown_terms(self, text: str) -> list[str]:
        """Index terms of ``text`` (backend analyzer) that occur in no chunk."""
        ...

    # ---- entity layer
    def all_mentions(self) -> list[Mention]: ...
    def replace_entity_graph(
        self,
        entities: list[Entity],
        assignments: dict[str, str],
        relationships: list[Relationship],
        decisions: list[ResolutionDecision],
        derived_mentions: list[Mention],
    ) -> None:
        """Atomically replace entities, relationships and decisions; ``derived_mentions``
        (corpus-adaptive "known_name" and "header" context mentions) replace previously derived ones."""
        ...
    def list_entities(self, entity_type: str | None = None) -> list[Entity]: ...
    def get_entity(self, entity_id: str) -> Entity | None: ...
    def all_relationships(self) -> list[Relationship]: ...
    def resolution_decisions(self) -> list[ResolutionDecision]: ...
